name: Deploy Computer Lambda Function

on:
  push:
    branches:
      - prod  # You can change this to the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create deployment package
      working-directory: lambdas/ComputersLambda
      run: |
        zip -r ComputersLambda.zip .
        mkdir artifacts
        mv ComputersLambda.zip artifacts/

    - name: Upload artifacts to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl private --follow-symlinks
      env:
        AWS_S3_BUCKET: 'shishapangma-artifacts'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "us-east-1"
        SOURCE_DIR: "lambdas/ComputersLambda/artifacts"

    - name: Deploy to Lambda
      working-directory: lambdas/ComputersLambda
      run: |
        aws lambda update-function-code --function-name ComputerLambda --s3-bucket shishapangma-artifacts --s3-key ComputersLambda.zip --region us-east-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "us-east-1"
