name: Deploy Site Manager Lambda Function

on:
  push:
    branches:
      - prod # You can change this to the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create deployment package
        working-directory: lambdas/SiteManagerLambda
        run: |
          zip -r SiteManagerLambda.zip .
          mkdir artifacts
          mv SiteManagerLambda.zip artifacts/

      - name: Upload artifacts to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl private --follow-symlinks
        env:
          AWS_S3_BUCKET: "shishapangma-artifacts"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          SOURCE_DIR: "lambdas/SiteManagerLambda/artifacts"

      - name: Deploy to Lambda
        working-directory: lambdas/SiteManagerLambda
        run: |
          aws lambda update-function-code --function-name SiteManagerLambda --s3-bucket shishapangma-artifacts --s3-key SiteManagerLambda.zip --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
