name: Deploy Store Lambda Function

on:
  push:
    branches:
      - main  # You can change this to the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create deployment package
      working-directory: lambdas/StoresLambda
      run: |
        zip -r package.zip .

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name GetStoreLambda \
          --zip-file fileb://package.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
