name: Deploy Store Lambda Function

on:
  push:
    branches:
      - main  # You can change this to the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create deployment package
      working-directory: lambdas/StoresLambda
      run: |
        zip -r package.zip .

    - name: Push Zip to S3
      uses: jakejarvis/s3-sync-action@v0.3.1
      env:
        SOURCE_DIR: './artifacts'
        AWS_REGION: 'eu-central-1'
        AWS_S3_BUCKET: 'zipped-lambda-artifacts'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
